#!/bin/bash
# Pre-removal script - runs BEFORE package files are removed
# Don't kill processes here as it interrupts dpkg

PACKAGE_NAME="whisperkey"
EXTENSION_UUID="whisperkey@whisperkey.app"

case "$1" in
    remove|purge)
        echo "Preparing to remove WhisperKey..."
        # Don't kill processes here - let postrm handle cleanup
        ;;
    upgrade)
        echo "Preparing to upgrade WhisperKey..."
        # Don't kill during upgrade - new version will replace files
        ;;
esac

exit 0


